name: flutter_web
version: 1.0.0
publish_to: "none"
description: A basic Flutter web app
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
