name: Basic Flutter Web Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web
