name: Basic Flutter Web Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release
        working-directory: flutter_web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: flutter_web/build/web
          publish_branch: gh-pages
